package com.example.ventana.model;

/**
 * The {@code GameLogic} class implements the core rules of the game.
 * It coordinates the progression of levels, time management per level,
 * and word validation by interacting with an {@code IWord} implementation
 * and maintaining the game state through an {@code IGameState} instance.
 *
 * <p>Main responsibilities include:</p>
 * <ul>
 *   <li>Validating user input against the current word.</li>
 *   <li>Advancing levels and adjusting time limits accordingly.</li>
 *   <li>Generating new words at each level.</li>
 *   <li>Resetting the game to its initial state.</li>
 * </ul>
 *
 * @author Nerie
 */
public class GameLogic implements IGameLogic {
    /** Word manager responsible for generating and retrieving words. */
    private final IWord wordManager;

    /** Object that stores and manages the current state of the game. */
    private final IGameState gameState;

    /**
     * Constructs a new {@code GameLogic} instance.
     *
     * @param wordManager an implementation of {@code IWord} used to generate and manage words.
     * @param gameState an implementation of {@code IGameState} used to store the game state.
     */
    public GameLogic(IWord wordManager, IGameState gameState) {
        this.wordManager = wordManager;
        this.gameState = gameState;
        gameState.setCurrentWord(wordManager.generateWord());
    }

    /**
     * Validates whether the user input matches the current word.
     *
     * @param input the word entered by the user.
     * @return {@code true} if the input matches the current word (case-insensitive),
     *         {@code false} otherwise.
     */
    @Override
    public boolean validateWord(String input) {
        return input.equalsIgnoreCase(gameState.getCurrentWord());
    }

    /**
     * Advances the game to the next level.
     * <p>Every 5 levels, the time per level is reduced by 2 seconds,
     * provided the time is greater than 2 seconds.</p>
     * <p>A new word is generated when moving to the next level.</p>
     */
    @Override
    public void nextLevel() {
        gameState.setLevel(gameState.getLevel() + 1);
        if (gameState.getLevel() % 5 == 0 && gameState.getTimePerLevel() > 2) {
            gameState.setTimePerLevel(gameState.getTimePerLevel() - 2);
        }
        gameState.setCurrentWord(wordManager.generateWord());
    }

    /**
     * Resets the game to its initial state.
     * <p>The level is set to 1, the time per level is reset to 20 seconds,
     * and a new word is generated.</p>
     */
    @Override
    public void resetGame() {
        gameState.resetGame();
        gameState.setCurrentWord(wordManager.generateWord());
    }

    /**
     * Returns the current level of the game.
     *
     * @return the current level.
     */
    @Override
    public int getLevel() {
        return gameState.getLevel();
    }

    /**
     * Returns the time allowed per level in seconds.
     *
     * @return the time per level.
     */
    @Override
    public int getTimePerLevel() {
        return gameState.getTimePerLevel();
    }

    /**
     * Returns the current word generated by the word manager.
     *
     * @return the current word.
     */
    @Override
    public String getCurrentWord() {
        return gameState.getCurrentWord();
    }
}