package com.example.ventana.model;

/**
 * The {@code IGameLogic} interface defines the contract for
 * implementing the core rules of the game.
 *
 * <p>Main responsibilities include:</p>
 * <ul>
 *   <li>Validating user input against the current word.</li>
 *   <li>Advancing levels and adjusting time limits.</li>
 *   <li>Providing access to the current level, time per level, and word.</li>
 * </ul>
 *
 * Implementations of this interface should coordinate with
 * {@code IWord} for word generation and {@code IGameState}
 * for storing the game state.
 *
 * @author Nerie
 */
public interface IGameLogic {
        /**
         * Validates whether the user input matches the current word.
         *
         * @param input the word entered by the user.
         * @return {@code true} if the input matches the current word (case-insensitive),
         *         {@code false} otherwise.
         */
        boolean validateWord(String input);

        /**
         * Advances the game to the next level.
         * <p>Implementations may adjust the time limit and generate a new word.</p>
         */
        void nextLevel();

        /**
         * Returns the current level of the game.
         *
         * @return the current level.
         */
        int getLevel();

        /**
         * Returns the time allowed per level in seconds.
         *
         * @return the time per level.
         */
        int getTimePerLevel();

        /**
         * Returns the current word generated by the word manager.
         *
         * @return the current word.
         */
        String getCurrentWord();
        void resetGame();
}